spring:
    h2:
      console:
          enabled: true
          path: /h2
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password: 1111
      driver-class-name: org.h2.Driver


    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect